font_family VictorMono Nerd Font
font_size 23.5
disable_ligatures cursor
clear_all_shortcuts yes
map page_up scroll_page_up
map page_down scroll_page_down
map ctrl+tab        send_text all \x1b[27;5;9~
map ctrl+shift+tab  send_text all \x1b[27;6;9~
map ctrl+shift+f5   load_config_file
map ctrl+shift+c copy_to_clipboard
map ctrl+shift+v paste_from_clipboard
map ctrl+shift+plus       change_font_size all +2.0
map ctrl+shift+equal      change_font_size all +2.0
map ctrl+shift+minus      change_font_size all -2.0
map ctrl+shift+underscore change_font_size all -2.0
map ctrl+backspace send_text all \x17
map ctrl+delete    send_text all \x1b[3;5~
#map alt+shift+.  next_tab
#map alt+shift+,  previous_tab
map ctrl+alt+up    send_text all \x1b[1;7A
map ctrl+alt+down  send_text all \x1b[1;7B
map ctrl+alt+right send_text all \x1b[1;7C
map ctrl+alt+left  send_text all \x1b[1;7D
map alt+shift+up    send_text all \x1b[1;4A
map alt+shift+down  send_text all \x1b[1;4B
map alt+shift+right send_text all \x1b[1;4C
map alt+shift+left  send_text all \x1b[1;4D
#;;  <BS><C-Del>
include ./theme.conf
