font_family VictorMono Nerd Font
font_size 23.5
map ctrl+backspace send_text all \x17
map ctrl+tab       send_text all \x1b[27;5;9~
map ctrl+shift+tab send_text all \x1b[27;6;9~
map alt+shift+.  next_tab
map alt+shift+,  previous_tab
map ctrl+alt+up    send_text all \x1b[1;7A
map ctrl+alt+down  send_text all \x1b[1;7B
map ctrl+alt+right send_text all \x1b[1;7C
map ctrl+alt+left  send_text all \x1b[1;7D
map alt+shift+up    send_text all \x1b[1;4A
map alt+shift+down  send_text all \x1b[1;4B
map alt+shift+right send_text all \x1b[1;4C
map alt+shift+left  send_text all \x1b[1;4D
#map ctrl+delete send_text all kill-word 
#;;  <BS><C-Del>
include ./theme.conf
