[alacritty]
meta.8 = A-<
meta.9 = A->

[kitty]
meta.8 = A-<
meta.9 = A->

[*tmux*]
meta.altgr = macro(C-insert c)
meta.8 = A-<
meta.9 = A->
meta.h = macro(C-insert h)
meta.j = macro(C-insert j)
meta.k = macro(C-insert k)
meta.l = macro(C-insert l)

[*chromium*]
alt.] = C-tab
alt.[ = C-S-tab
alt.t = C-t
