# Config for sworkstyle
#
# You can rename workspaces based on the exact application names or by generic pattern.
# When it could not match anything it will use the fallback.
#
# format:
#
# 	'{pattern}' = '{icon}'
#
# pattern: Can either be the exact "app_name" (app_id/class) of the window or a regex string in the format of `"/{regex}/"` which will match the window "title".
# icon: Your beatifull icon
#
# verbose format:
# 
#	'{pattern}' = { type = 'generic' | 'exact', value = '{icon}' }
#
#
# If it couldn't match something it will print:
# 
# WARN [sworkstyle:config] No match for '{app_name}' with title '{title}' 
#
# You can use {title} to do a generic matching 
# You can use {app_name} to do an exact match

fallback = ''
[matching]
'/Chromium$/' = ''
'org.qt-project.qtcreator' = ''
'DBeaver' = '󰡦'
'/Firefox$/' = ''
'org.kde.okular' = '󰊪'
'/^htop ?\w*/' = ''
'/node/' = '󰎙'
'/npm/' = '󰛷'
'/^nvim \w*/' = ''
'/^vim \w*/' = ''
'/yarn/' = ''
'Alacritty' = ''
'Chia Blockchain' = ' '
'Chromium' = ''
'designer' = ''
'Element' = ''
'Emacs' = ' '
'Gimp' = ''
'GitHub Desktop' = ' '
'Google-chrome' = ' '
'Insomnia' = ' '
'kicad' = ''
'Mysql-workbench-bin' = '󱢴'
'Milkman' = ''
'Nightly' = ''
'Postman' = ''
'Qt6ct' = ''
'SQLiteStudio' = ''
'Signal' = ' '
'Slack' = ' '
'Spotify' = ''
'Steam' = ''
'Thunderbird' = ' '
'Toplevel' = ''
'VirtualBox' = ' '
'balena-etcher' = ''
'bitwarden' = ''
'blender' = '󰂫'
'code' = ''
'code-oss' = ' '
'dconf-editor' = '󰊬'
'discord' = '󰙯'
'eog' = ' '
'org.kde.kdenlive' = ''
'evince' = '󰈦'
'file-roller' = ''
'firefoxdeveloperedition' = ''
'foot' = ' '
'font-manager' = '󰛖'
'fr.handbrake.ghb' = '󱁆'
'gaupol' = '󰨖'
'kitty' = ''
'jetbrains-studio' = ' '
'libreoffice-calc' = ''
'libreoffice-impress' = '󰐨'
'libreoffice-startcenter' = '󰏆'
'libreoffice-writer' = '󰈬'
'mkvtoolnix-gui' = ''
'mpv' = ''
'org.gnome.Calculator' = ''
'org.gnome.Nautilus' = ''
'org.gnome.TextEditor' = '󱞎'
'pavucontrol' = ''
'com.github.treagod.spectator' = '󰛐'
'Spectator' = '󰊪 '
'tmux' = ''
'qBittorrent' = ''
'qimgv' = '󰼀'
'qt5ct' = ''
'qt6ct' = ''
'thunderbird' = ' '
