unbind-key -a -T root
unbind r
bind r source-file ~/.config/tmux/tmux.conf 

set -s extended-keys on
set -s escape-time 0
set -as terminal-features 'xterm*:extkeys'
set -g prefix M-a
set-option -g repeat-time 0
set -g base-index 1
set -g pane-base-index 1
set-window-option -g pane-base-index 1
set-option -g renumber-windows on
set-option -sa terminal-overrides ",xterm*:Tc"
set-window-option -g mode-keys vi

bind-key -T copy-mode-vi v send-keys -X begin-selection
bind-key -T copy-mode-vi C-v send-keys -X rectangle-toggle
bind-key -T copy-mode-vi y send-keys -X copy-selection-and-cancel

bind-key -n M-1 selectw -t 1
bind-key -n M-2 selectw -t 2
bind-key -n M-3 selectw -t 3
bind-key -n M-4 selectw -t 4
bind-key -n M-5 selectw -t 5
bind-key -n M-6 selectw -t 6
bind-key -n M-7 selectw -t 7
bind-key -n M-8 selectw -t 8
bind-key -n M-9 selectw -t 9

bind-key -n C-S-Tab prev
bind-key -n C-Tab  next
bind-key -n C-F4 kill-pane
set -g mouse on
set-option -g status-position top

# bind-key h select-pane -L
# bind-key j select-pane -D
# bind-key k select-pane -U
# bind-key l select-pane -R

bind -n M-%   split-window -v -c "#{pane_current_path}"
bind -n 'M-"' split-window -h -c "#{pane_current_path}"

#List of plugins
set -g @plugin 'catppuccin/tmux'
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'jamesoff/tmux-loadavg'
set -g @plugin 'christoomey/vim-tmux-navigator'
# Smart pane switching with awareness of Vim splits.
# See: https://github.com/christoomey/vim-tmux-navigator
set -g @vim_navigator_mapping_left  "C-h S-Left"  # use C-h and C-Left
set -g @vim_navigator_mapping_right "C-l S-Right "
set -g @vim_navigator_mapping_up    "C-k S-Up"
set -g @vim_navigator_mapping_down  "C-j S-Down"
set -g @vim_navigator_mapping_prev ""  # removes the C-\ binding

# bind-key -n S-Left  select-pane -L
# bind-key -n S-Down  select-pane -D
# bind-key -n S-Up    select-pane -U
# bind-key -n S-Right select-pane -R
bind-key -n M-C-S-Left  resize-pane -L 1
bind-key -n M-C-S-Down  resize-pane -D 1
bind-key -n M-C-S-Up    resize-pane -U 1
bind-key -n M-C-S-Right resize-pane -R 1

#set -g @plugin 'jimeh/tmuxifier' # doesn't work. gave up 
#set -g @plugin 'tmux-plugin/tmux-yank'

# Other examples:
# set -g @plugin 'github_username/plugin_name'
# set -g @plugin 'github_username/plugin_name#branch'
# set -g @plugin 'git@github.com:user/plugin'
#oo set -g @plugin 'git@bitbucket.com:user/plugin'
set -g @catppuccin_window_left_separator ""
set -g @catppuccin_window_right_separator " "
set -g @catppuccin_window_middle_separator "█ "
set -g @catppuccin_window_number_position "left"

set -g @catppuccin_window_default_fill "number"
set -g @catppuccin_window_default_text "#W"

set -g @catppuccin_window_current_fill "number"
set -g @catppuccin_window_current_text "#W"

set -g @catppuccin_status_modules_right "session date_time"
set -g @catppuccin_status_left_separator "█"
set -g @catppuccin_status_right_separator "█"

set -g @catppuccin_date_time_text "%a%d %H:%M"

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'
